name: tws_project
description: Todo App dengan reminder

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  flutter_timezone: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather_24pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Merriweather_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Merriweather_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Merriweather_24pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Merriweather_24pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Merriweather_24pt-Italic.ttf
          style: italic
